### ISSUE TITLE
GOT-OCR2  Current CUDA Device does not support bfloat16. Please switch dtype to float16.

### ISSUE THREAD

**Issue by 40740** [heshengtao/comfyui_LLM_party#122]
`!!! Exception during processing !!! Current CUDA Device does not support bfloat16. Please switch dtype to float16.
Traceback (most recent call last):
  File "/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "//ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "//ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "//ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "//ComfyUI/custom_nodes/comfyui_LLM_party/custom_tool/GOT-OCR2.py", line 81, in time
    res=perform_ocr(model_name_or_path, device, ocr_type, image_path,ocr_box, ocr_color, multi_crop,render,out_dir_path)
  File "//ComfyUI/custom_nodes/comfyui_LLM_party/custom_tool/GOT-OCR2.py", line 34, in perform_ocr
    res = model.chat(tokenizer, image_path, ocr_type=ocr_type, ocr_box=ocr_box, ocr_color=ocr_color)
  File "/root/.cache/huggingface/modules/transformers_modules/stepfun-ai/GOT-OCR2_0/cf6b7386bc89a54f09785612ba74cb12de6fa17c/modeling_GOT.py", line 581, in chat
    with torch.autocast("cuda", dtype=torch.bfloat16):
  File "/opt/conda/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 305, in __init__
    raise RuntimeError(
RuntimeError: Current CUDA Device does not support bfloat16. Please switch dtype to float16.`、

-------------------------------------------------------------------------------

`!!! Exception during processing !!! Expected one of cpu, cuda, ipu, xpu, mkldnn, opengl, opencl, ideep, hip, ve, fpga, ort, xla, lazy, vulkan, mps, meta, hpu, mtia, privateuseone device type at start of device string: auto
Traceback (most recent call last):
  File "//ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "//ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "//ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "//ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "//ComfyUI/custom_nodes/comfyui_LLM_party/custom_tool/GOT-OCR2.py", line 81, in time
    res=perform_ocr(model_name_or_path, device, ocr_type, image_path,ocr_box, ocr_color, multi_crop,render,out_dir_path)
  File "//ComfyUI/custom_nodes/comfyui_LLM_party/custom_tool/GOT-OCR2.py", line 25, in perform_ocr
    model = model.to(device=device,  dtype=torch.float16)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/big_modeling.py", line 448, in wrapper
    to_device = torch._C._nn._parse_to(*args, **kwargs)[0]
RuntimeError: Expected one of cpu, cuda, ipu, xpu, mkldnn, opengl, opencl, ideep, hip, ve, fpga, ort, xla, lazy, vulkan, mps, meta, hpu, mtia, privateuseone device type at start of device string: auto`

**Comment by heshengtao** [comment]
Fixed, now this node can be changed to any dtype
