### ISSUE TITLE
UnicodeEncodeError: 'locale' codec can't encode character '\u5e74' in position 2: encoding error

### ISSUE THREAD

**Issue by TrentHunter82** [heshengtao/comfyui_LLM_party#28]
After Updating Comfy and all of my nodes yesterday I got this error:

!!! Exception during processing!!! 'locale' codec can't encode character '\u5e74' in position 2: encoding error
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 148, in recursive_execute
    obj = class_def()
          ^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_LLM_party\llm.py", line 448, in __init__
    self.id =  current_time.strftime("%Y年%m月%d日%H时%M分%S秒")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'locale' codec can't encode character '\u5e74' in position 2: encoding error

Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 148, in recursive_execute
    obj = class_def()
          ^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_LLM_party\llm.py", line 448, in __init__
    self.id =  current_time.strftime("%Y年%m月%d日%H时%M分%S秒")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'locale' codec can't encode character '\u5e74' in position 2: encoding error

Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 148, in recursive_execute
    obj = class_def()
          ^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_LLM_party\llm.py", line 448, in __init__
    self.id =  current_time.strftime("%Y年%m月%d日%H时%M分%S秒")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'locale' codec can't encode character '\u5e74' in position 2: encoding error

**Comment by heshengtao** [comment]
I deleted the Chinese characters in the id. Please let me know if the problem is solved after updating the plugin.

**Comment by TrentHunter82** [comment]
That worked thank you so much!!!
