### ISSUE TITLE
ModuleNotFoundError: No module named 'jax.numpy'; 'jax' is not a package

### ISSUE THREAD

**Issue by Pythonpa** [heshengtao/comfyui_LLM_party#35]
# When started the latest version,it shows this error message
Traceback (most recent call last):
  File "C:\ComfyUI\nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI\custom_nodes\comfyui_LLM_party\__init__.py", line 8, in <module>
    from .llm import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\ComfyUI\custom_nodes\comfyui_LLM_party\llm.py", line 1873, in <module>
    load_custom_tools()
  File "C:\ComfyUI\custom_nodes\comfyui_LLM_party\llm.py", line 1851, in load_custom_tools
    spec.loader.exec_module(module)
  File "C:\ComfyUI\custom_nodes\comfyui_LLM_party\custom_tool\chatTTS_node.py", line 4, in <module>
    import ChatTTS
  File "C:\ComfyUI\python\lib\site-packages\ChatTTS\__init__.py", line 1, in <module>
    from .core import Chat
  File "C:\ComfyUI\python\lib\site-packages\ChatTTS\core.py", line 18, in <module>
    from .model import DVAE, GPT, gen_logits
  File "C:\ComfyUI\python\lib\site-packages\ChatTTS\model\__init__.py", line 1, in <module>
    from .dvae import DVAE
  File "C:\ComfyUI\python\lib\site-packages\ChatTTS\model\dvae.py", line 9, in <module>
    from vector_quantize_pytorch import GroupedResidualFSQ
  File "C:\ComfyUI\python\lib\site-packages\vector_quantize_pytorch\__init__.py", line 2, in <module>
    from vector_quantize_pytorch.residual_vq import ResidualVQ, GroupedResidualVQ
  File "C:\ComfyUI\python\lib\site-packages\vector_quantize_pytorch\residual_vq.py", line 18, in <module>
    from einx import get_at
  File "C:\ComfyUI\python\lib\site-packages\einx\__init__.py", line 5, in <module>
    from . import backend
  File "C:\ComfyUI\python\lib\site-packages\einx\backend\__init__.py", line 1, in <module>
    from .register import register_for_module, register, get, backends, numpy
  File "C:\ComfyUI\python\lib\site-packages\einx\backend\register.py", line 53, in <module>
    register_for_module("jax", _jax.create)
  File "C:\ComfyUI\python\lib\site-packages\einx\backend\register.py", line 19, in register_for_module
    register(backend_factory())
  File "C:\ComfyUI\python\lib\site-packages\einx\backend\_jax.py", line 11, in create
    import jax.numpy as jnp
ModuleNotFoundError: No module named 'jax.numpy'; 'jax' is not a package

**Comment by heshengtao** [comment]
The current vector_quantize_pytorch no longer rely on jax, I think you can try to update the version of vector_quantize_pytorch, or directly update the version of chatTTS.

**Comment by heshengtao** [comment]
The current vector_quantize_pytorch no longer rely on jax, I think you can try to update the version of vector_quantize_pytorch, or directly update the version of chatTTS

**Comment by Pythonpa** [comment]
> The current vector_quantize_pytorch no longer rely on jax, I think you can try to update the version of vector_quantize_pytorch, or directly update the version of chatTTS

ok,the version of ChatTTS and  vector-quantize-pytorch, both of them are the latest, ChatTTS==0.1.1   vector-quantize-pytorch=1.15.3.
By the way, my OS is Windows 10. Could it be related to incompatible system versions?

**Comment by guobalove** [comment]
I noticed that the file paths in your einx folder are different from mine, so I checked the version of my einx library and found it's 0.3.0.

**Comment by Pythonpa** [comment]
> I noticed that the file paths in your einx folder are different from mine, so I checked the version of my einx library and found it's 0.3.0.

Weired,my einx also is 0.3.0
> [SD-Launcher] C:\ComfyUI>C:\ComfyUI\python\python.exe -m pip show einx
Name: einx
Version: 0.3.0
Summary: Universal Tensor Operations in Einstein-Inspired Notation for Python
Home-page: https://github.com/fferflo/einx
Author: Florian Fervers
Author-email: florian.fervers@gmail.com
License: MIT
Location: c:\comfyui\python\lib\site-packages
Requires: frozendict, numpy, sympy
Required-by: vector-quantize-pytorch

**Comment by heshengtao** [comment]
My system is Win11, and everything else is the same as you. There is no jax library in my environment. But I can run normally.After I tried to install jax & jaxlib, it can also run, that is to say, whether there is jax & jaxlib or not will not affect the operation of chatTTS. If you don't need to use chatTTS, you can directly delete C:\ ComfyUI\ custom_nodes\ comfyui_LLM_party\ custom_tool\ chatTTS_node.py, this error will disappear.

**Comment by Pythonpa** [comment]
> My system is Win11, and everything else is the same as you. There is no jax library in my environment. But I can run normally.After I tried to install jax & jaxlib, it can also run, that is to say, whether there is jax & jaxlib or not will not affect the operation of chatTTS. If you don't need to use chatTTS, you can directly delete C:\ ComfyUI\ custom_nodes\ comfyui_LLM_party\ custom_tool\ chatTTS_node.py, this error will disappear.
## ok, thanks,will have a try.

**Comment by Pythonpa** [comment]
> My system is Win11, and everything else is the same as you. There is no jax library in my environment. But I can run normally.After I tried to install jax & jaxlib, it can also run, that is to say, whether there is jax & jaxlib or not will not affect the operation of chatTTS. If you don't need to use chatTTS, you can directly delete C:\ ComfyUI\ custom_nodes\ comfyui_LLM_party\ custom_tool\ chatTTS_node.py, this error will disappear.

I found this [issues about jax](https://github.com/google/jax/issues/10605#issuecomment-1163389089) ,maybe which is `Related to einx\tracer`

**Comment by heshengtao** [comment]
It is very likely that another person has reported the same error, and his computer has a dependency that contains a file called jax.py, while mine does not.

**Comment by fferflo** [comment]
It looks like the traceback of the error is in a codepath that can only execute if `"jax" in sys.modules`. So likely there is a module with name "jax" that has already been imported, such as a file jax.py, but it is not the Jax library itself. You could check which file has been imported
```python
>>> sys.modules["jax"]
<module 'jax' from '.../site-packages/jax/__init__.py'>
```
and whether importing Jax manually gives the same error:
```python
import jax.numpy as jnp
```

**Comment by heshengtao** [comment]
In the latest version of my node, I import jax before importing chatTTS, which avoids einx importing jax. I hope this fixes your problem. If there is still an error, my node library will block the import of chatTTS without affecting the use of other nodes.

**Comment by Pythonpa** [comment]
The PARTY node can now be started and used normally, but after observing the startup logs, it is actually running by blocking the import of chatTTS.
![image](https://github.com/user-attachments/assets/d3b908a8-3a4f-4116-87a7-a9bcb941118f)

**Comment by heshengtao** [comment]
This bug has been unable to be reproduced due to multiple of our computers. If you don't need the chatTTS function for the time being, it may take us a long time to solve this problem. Thank you very much for your feedback. We will notify you immediately when we solve the problem.

**Comment by heshengtao** [comment]
https://github.com/jtydhr88/ComfyUI-Unique3D/issues/8#issuecomment-2201885173
Referring to this answer, jax was disabled by the autumn leaf package. We can reproduce this bug on the autumn leaf package. If you need to use chatTTS, you can use the original comfyui to start, or use the iron pot to start.
参考这个回答，jax被秋叶包给禁用了，我们在秋叶包上可以复现这个BUG，如果你需要使用chatTTS,可以使用原版comfyui启动，或者使用铁锅炖启动。

**Comment by Pythonpa** [comment]
> [jtydhr88/ComfyUI-Unique3D#8 (comment)](https://github.com/jtydhr88/ComfyUI-Unique3D/issues/8#issuecomment-2201885173) Referring to this answer, jax was disabled by the autumn leaf package. We can reproduce this bug on the autumn leaf package. If you need to use chatTTS, you can use the original comfyui to start, or use the iron pot to start. 参考这个回答，jax被秋叶包给禁用了，我们在秋叶包上可以复现这个BUG，如果你需要使用chatTTS,可以使用原版comfyui启动，或者使用铁锅炖启动。

Okay, I will try using the Docker version of comfyui later to see if there will be any problems

**Comment by fferflo** [comment]
The problem should also be fixed with the latest source version of einx (see [this commit](https://github.com/fferflo/einx/commit/affbd5c94064e344f52fb0fdb5e34d3b8e7bc686)), so you could try updating einx:

```
pip install --upgrade git+https://github.com/fferflo/einx.git
```

**Comment by BertWang** [comment]
果然.秋叶包的問題。國內大都還是分二大主流.秋叶包/铁锅炖啓動。看來要美好體驗..只能走向.. 铁锅炖启动。在掛回秋叶包
