### ISSUE TITLE
TypeError: install_package() got an unexpected keyword argument 'custom_command'

### ISSUE THREAD

**Issue by Myra009** [heshengtao/comfyui_LLM_party#56]
Traceback (most recent call last):
  File "C:\ai\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\nodes.py", line 1941, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ai\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\comfyui_LLM_party\__init__.py", line 1, in <module>
    from .install import (
  File "C:\ai\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\comfyui_LLM_party\install.py", line 364, in <module>
    install_llama(system_info)
  File "C:\ai\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\comfyui_LLM_party\install.py", line 181, in install_llama
    install_package("llama-cpp-python", custom_command=custom_command)
TypeError: install_package() got an unexpected keyword argument 'custom_command'

节点安装后，打开comfyui的时候出错

**Comment by heshengtao** [comment]
这确实是一个严重的bug，我会在今晚修复一下

**Comment by heshengtao** [comment]
已修复
