### ISSUE TITLE
centos平台报错：ComfyUI/custom_nodes/comfyui_LLM_party module for custom nodes: [Errno 2] No such file or di rectory: 'dpkg'

### ISSUE THREAD

**Issue by rwywenyi** [heshengtao/comfyui_LLM_party#61]
请问如何解决该报错，很着急

> 找不到llama_cpp模块
Traceback (most recent call last):
  File "/aigc-nas01/renwenyi/ComfyUI/nodes.py", line 1941, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/aigc-nas01/renwenyi/ComfyUI/custom_nodes/comfyui_LLM_party/__init__.py", line 1, in <module>
    from .install import (
  File "/aigc-nas01/renwenyi/ComfyUI/custom_nodes/comfyui_LLM_party/install.py", line 391, in <module>
    install_portaudio()
  File "/aigc-nas01/renwenyi/ComfyUI/custom_nodes/comfyui_LLM_party/install.py", line 337, in install_portaudio
    result = subprocess.run(["dpkg", "-s", "libportaudio2"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/home/work/anaconda3/envs/animate_anyone/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/work/anaconda3/envs/animate_anyone/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/work/anaconda3/envs/animate_anyone/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dpkg'

**Comment by heshengtao** [comment]
更新party，昨天有人提了一样的issue，修复了

**Comment by rwywenyi** [comment]
> 更新party，昨天有人提了一样的issue，修复了

使用此issue中的代码，依旧报错，没有解决问题，才来提新的issue

**Comment by heshengtao** [comment]
ok，我晚上回来改一下，适配一下centos系统

**Comment by heshengtao** [comment]
修复了，你测试一下吧

**Comment by heshengtao** [comment]
请问是否能够成功运行？

**Comment by rwywenyi** [comment]
> 请问是否能够成功运行？如果BUG已修复，请提示我关闭issue

非常感谢，已成功在centos系统运行，可以关闭issue了，再次感谢。
