### ISSUE TITLE
Error: Extension named 'party.ShowText' already registered.     

### ISSUE THREAD

**Issue by snoche** [heshengtao/comfyui_LLM_party#94]
**Describe the bug**
ShowText stop working for me after the confyui ui update a few weeks ago

![image](https://github.com/user-attachments/assets/7fca28de-cb53-49ce-96f1-25ba1f306e20)

**To Reproduce**
when opening Confyui in the browser console I got this error:
app.ts:1725 Error loading extension /extensions/party/showtext_party.js Error: Extension named 'party.ShowText' already registered.
    at ComfyApp.registerExtension (app.ts:2856:13)
    at showtext_party.js:5:5
    
This file is been copied in the web/extensions/party but looks like is already registed

![image](https://github.com/user-attachments/assets/15010842-708b-493b-9489-40b439a1dfed)

**On executing error:**
showText.js:45 Uncaught TypeError: Cannot read properties of undefined (reading 'text')
    at nodeType.onExecuted (showText.js:45:33)
    at nodeType.onExecuted (easy_videooutput_node.js:240:41)
    at ComfyApi.<anonymous> (app.ts:1629:16)
    at os.invokeTarget (AdGuard Popup Blocker.user.js:455:270074)
    at gt (AdGuard Popup Blocker.user.js:455:287512)
    at eval (AdGuard Popup Blocker.user.js:455:271601)
    at eval (AdGuard Popup Blocker.user.js:455:270275)
    at ComfyApi.dispatchEvent (AdGuard Popup Blocker.user.js:455:269497)
    at WebSocket.<anonymous> (api.ts:202:20)
    
If I delete the file from comfyui_LLM_party\web\js  I don't get the already registered error and the showText from customScripts works again. It could be a conflict between the other package?

![image](https://github.com/user-attachments/assets/22244ecc-b3cc-491b-9fa9-a666f9939999)

By the other hand if I delete showText from ComfyUI-Custom-Scripts nothing is fixed
https://github.com/pythongosssss/ComfyUI-Custom-Scripts

![image](https://github.com/user-attachments/assets/b59db7ab-19f7-4041-859e-c4700b5efc9c)

![image](https://github.com/user-attachments/assets/a7cdd720-9be7-48b6-845a-e8862890d43f)

![image](https://github.com/user-attachments/assets/361258de-342c-4078-b083-9f539d9c1a80)

I tried deleting full ComfyUI-Custom-Scripts folder and nothing is fix neither, so looks like it could be LLM party registering twice or something? and breaks also the other node? I am so confuse, no one else has this issue?

**Comment by heshengtao** [comment]
I tried to fix this issue. Please update to the latest LLM party to see if it has been fixed.

**Comment by snoche** [comment]
That fixed the error of redeclaration thanks

FYI: The issue I was having was different, it was Adguard, even not enabled for local host and disabling Adguard was still blocking something, I had to allow "Unsafe content" con the extension to allow this too work.
